algoritmo "teste"
var 
 x, y : inteiro
 z : real

 funcao fatorial( n : inteiro ) inteiro
 var
   f, i : inteiro
 inicio
   f <- 1
   i <- 0
   retorne f
 fimfuncao

 funcao xpto() inteiro
 var
   z : real
 inicio
    retorne f
 fimfuncao

 procedimento procteste(x : real)
 var
   z : real
 inicio
    f <- 30
 fimprocedimento

 procedimento novoteste()
 var
   z : real
 inicio
    f <- 30
 fimprocedimento

inicio
   x <- 10
   y <- y * 3
fimalgoritmo
